# tests-ut
# build-docker

name: gist-python-app
#runs-on: self-hosted
on: [push]
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: "Checkout current branch"
        uses: actions/checkout@v4
      - run: |
          pip3 install -r requirements.txt 
      - name: "Run unit tests"
        run: |
          pytest tests

