# tests-ut
# build-docker

name: gist-python-app
#runs-on: self-hosted
on: [push]
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - run: |
          pip install -r requirements.txt
      - run: |
          pytest tests

