# tests-ut
# build-docker
# publish artifacts(pkg, images)

name: gist-python-app
#runs-on: self-hosted
on: [push]
jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: "Checkout current branch"
        uses: actions/checkout@v4
      - run: |
          pip3 install -r requirements.txt 
      - name: "Run unit tests"
        run: |
          pytest tests
  run-docker-build:
    needs: run-unit-tests
    runs-on: self-hosted
    steps:
    - name: "Checkout current branch"
      uses: actions/checkout@v4
    - run: |
        docker build -t gits-app:${GITHUB_RUN_ID} .

